# Site
name: 'HP C-13 Imaging Parameters'
description: 'A place for shared HP C-13 Imaging Parameters'
logo: 'assets/images/HMTRC-logo-crop.jpg'
favicon: 'assets/images/HMTRC-logo-crop.jpg'
baseurl: '/'
avatar: 'assets/images/HMTRC-logo-crop.jpg'
email: 'hyperpolarizedmri@ucsf.edu'
# disqus: 'smartgram'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
      
# Syntax
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 20


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
